---
#            _     _ _             _              ___            _        
#   __ _  __| | __| | | ___   __ _(_)_ __  ___   / / |_ __ _ ___| | _____ 
#  / _` |/ _` |/ _` | |/ _ \ / _` | | '_ \/ __| / /| __/ _` / __| |/ / __|
# | (_| | (_| | (_| | | (_) | (_| | | | | \__ \/ / | || (_| \__ \   <\__ \
#  \__,_|\__,_|\__,_|_|\___/ \__, |_|_| |_|___/_/   \__\__,_|___/_|\_\___/
#                            |___/                                        
# tasks file for ar-addlogins
- name: wheel group should be created
  group: name=wheel state=present

- block:
    - name: Each group should be created
      group: >
        name={{ item.group }}
        gid={{ item.gid }}
        state=present
      with_items: "{{ addlogins.unixusers }}"

    - name: Each user should be created
      when: addlogins.enabled == true
      user: >
        name={{ item.username }} 
        password={{ item.password }}
        uid={{ item.uid }}
        group={{ item.group }} 
        shell={{ item.shell }}
        home={{ item.home }}
        createhome=yes
        state=present
      with_items: "{{ addlogins.unixusers }}"

    - name: Belongs to other group
      user: >
        name={{ item.1 }} 
        groups={{ item.0.group }}
        state=present
      with_subelements:
        - "{{ addlogins.belongsto }}"
        - 'users'
  when: addlogins.enabled == true

